name: Build XBAP Project

# 手动触发和自动触发
on:
  workflow_dispatch: # 手动触发
  push: # 自动触发
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 步骤 1: 检出代码
    - name: Checkout Code
      uses: actions/checkout@v3

    # 步骤 2: 设置 .NET Framework 环境
    - name: Setup .NET Framework
      run: |
        choco install dotnetfx --version=4.8
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools"

    # 步骤 3: 清理构建目录
    - name: Clean Build Directories
      run: |
        if exist obj rmdir /s /q obj
        if exist bin rmdir /s /q bin
      shell: cmd

    # 步骤 4: 使用 MSBuild 编译项目
    - name: Build with MSBuild
      run: |
        msbuild powershell.sln /p:Configuration=Release /p:SignManifests=false /p:TargetFrameworkVersion=v4.8

    # 步骤 5: 上传编译产物供下载
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build-Output # Artifact 文件的名称
        path: bin/Release/ # 编译输出路径
        retention-days: 7 # 保存 7 天（默认 90 天）
