name: Build XBAP Project

# 手动触发 Workflow
on:
  workflow_dispatch: # 手动触发事件，用户可以通过 GitHub Actions 页面手动运行
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 步骤 1: 检出代码
    - name: Checkout Code
      uses: actions/checkout@v3

    # 步骤 2: 设置 .NET Framework 环境
    - name: Setup .NET Framework
      run: |
        choco install dotnetfx --version=4.8
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools"

    # 步骤 3: 安装 NuGet 依赖
    - name: Install NuGet Dependencies
      run: |
        nuget restore powershell.sln

    # 步骤 4: 清理构建文件夹
    - name: Clean Build Directories
      run: |
        if exist obj rmdir /s /q obj
        if exist bin rmdir /s /q bin

    # 步骤 5: 使用 MSBuild 编译
    - name: Build with MSBuild
      run: |
        msbuild powershell.sln /p:Configuration=Release /p:SignManifests=false /p:TargetFrameworkVersion=v4.8

    # 步骤 6: 上传编译产物
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build-Output # 设置 Artifact 名称
        path: bin/Release/ # 上传的文件路径
