name: Build XBAP Project

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install .NET Framework 4.8 Developer Pack
    - name: Install .NET Framework 4.8 Developer Pack
      run: |
        choco install netfx-4.8-devpack -y

    # Step 3: Install Visual Studio 2019 Build Tools
    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools" -y

    # Step 4: Add MSBuild to PATH
    - name: Add MSBuild to PATH
      run: |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin" >> $env:GITHUB_PATH

    # Step 5: Clean Build Directories
    - name: Clean Build Directories
      run: |
        if exist bin rmdir /s /q bin
        if exist obj rmdir /s /q obj
      shell: cmd

    # Step 6: Build with MSBuild
    - name: Build with MSBuild
      run: |
        msbuild powershell.sln /p:Configuration=Release /p:SignManifests=false /p:OutDir=$(System.DefaultWorkingDirectory)\bin\Release

    # Step 7: Verify Build Output
    - name: Verify Build Output
      run: |
        echo "Listing files in bin\Release directory:"
        dir bin\Release /s

    # Step 8: Upload Build Artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build-Output
        path: bin/Release/
        retention-days: 7
        if-no-files-found: warn
