name: Build XBAP Project

# 触发条件：手动触发、代码推送或 PR
on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 检出代码
    - name: Checkout Code
      uses: actions/checkout@v3

    # 安装 .NET Framework 4.8 Developer Pack
    - name: Install .NET Framework 4.8 Developer Pack
      run: |
        choco install netfx-4.8-devpack -y

    # 安装 Visual Studio 2019 Build Tools
    - name: Install Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools" -y

    # 将 MSBuild 路径添加到环境变量
    - name: Add MSBuild to PATH
      run: |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin" >> $env:GITHUB_PATH

    # 清理构建目录
    - name: Clean Build Directories
      run: |
        if exist obj rmdir /s /q obj
        if exist bin rmdir /s /q bin
      shell: cmd

    # 使用 MSBuild 构建项目
    - name: Build with MSBuild
      run: |
        msbuild powershell.sln /p:Configuration=Release /p:SignManifests=false /p:TargetFrameworkVersion=v4.8

    # 上传构建产物
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build-Output
        path: bin/Release/ # 编译输出路径
        retention-days: 7
